INSERT INTO originator (code, description) VALUES ( 'STP', 'Sumgait Technologies Park') ON CONFLICT(code) DO NOTHING;
INSERT INTO originator (code, description) VALUES ( 'KLN', 'Kolin') ON CONFLICT(code) DO NOTHING;
INSERT INTO originator (code, description) VALUES ( 'PRO', 'Proyapi/Prokon') ON CONFLICT(code) DO NOTHING;
INSERT INTO originator (code, description) VALUES ( 'AZR', 'Azroksan') ON CONFLICT(code) DO NOTHING;
INSERT INTO originator (code, description) VALUES ( 'RKT', 'Roketsan') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( '3DS', '3D Model/Isometric Sketch') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'BOQ', 'Bill of Quantities') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'CLC', 'Calculation') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'DST', 'Data Sheets') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'DTQ', 'Design Technical Query') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'DVR', 'Deviation Request') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'DWG', 'Drawing') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'ENI', 'Engineering Instruction') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'FRM', 'Forms') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'GAD', 'General Arrangement Drawing') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'IDF', 'Identification Form') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'ITP', 'Inspection and Testing Plan') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'JSA', 'Job Safety Assessment') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'LOG', 'Log') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'LST', 'List') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'MAP', 'Master Plan / Area Plan') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'MAR', 'Material Approval Request') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'MES', 'Method Statement') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'MOM', 'Minutes of Meeting') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'MRQ', 'Material Requisition') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'MTO', 'Material Take off') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'NCR', 'Non Conformance Report') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'ORG', 'Organization Chart') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'PLN', 'Plan') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'PRC', 'Procedure') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'REP', 'Report') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'REQ', 'Requirement') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'RFI', 'Request For Inspection') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'SOW', 'Scope Of Work') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'SPE', 'Specification') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'SSD', 'Steelwork Structures') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'STI', 'Site Instruction') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'STN', 'Standards') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'STQ', 'Site Technical Query') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'TOR', 'Terms Of Reference') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'SRF', 'Supplier Vendor Approval Request') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'SAR', 'Subcontractor Approval Request') ON CONFLICT(code) DO NOTHING;
INSERT INTO document_type (code, description) VALUES ( 'SCH', 'Schedule') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'DD', 'Design Development') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'CV', 'Civil') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'AR', 'Architectural') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'MC', 'Mechanical') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'EL', 'Electrical') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'EQ', 'Equipment') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'WE', 'Weak Curent') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'QM', 'Quality Management (QA/QC)') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'HS', 'Health Safety and Environment') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'CP', 'Contract & Procurement Management') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'PC', 'Planning & Cost-Control') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'PM', 'Project Management') ON CONFLICT(code) DO NOTHING;
INSERT INTO discipline (code, description) VALUES ( 'CO', 'Commissioning & Operation') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GN00', 'General') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IN00', 'Infrastructure') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'MB00', 'Mobilisation') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES01', 'ESB-01-AP Storage Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES02', 'ESB-02-AP Storage Handling Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES03', 'ESB-03-Fuse Storage') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES04', 'ESB-04-Warhead Storage Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES05', 'ESB-05-Ammunition Storage Building-1') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES06', 'ESB-06-Ammunition Storage Building-2') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES07', 'ESB-07-Ammunition Storage Building-3') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES08', 'ESB-08-Ammunition Storage Building-4') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'ES09', 'ESB-09-Storage for Destruction') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW01', 'EWB-01-Hammer Mill Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW02', 'EWB-02-AP Storage and Conditioning Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW03', 'EWB-03-Mixer Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW04', 'EWB-04-Premix and Mixbowl Cleaning Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW05', 'EWB-05-Propellant Casting Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW06', 'EWB-06-Propellant Mandrel Disassembly Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW07', 'EWB-07-X-ray and Quality Control Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW08', 'EWB-08-Laboratory Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW09', 'EWB-09-Small Scale Propellant Assembly Firing Test') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW10', 'EWB-10-Conditioning Building (Small Scale Propellant Assembly)') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW11', 'EWB-11-Warhead Filling and Assembly Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW12', 'EWB-12-Warhead Press Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'EW13', 'EWB-13-Final Assembly Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF01', 'GFB-01-Main Entrance Check Point') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF02', 'GFB-02-Main Entrance Building (pedestrian)') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF03', 'GFB-03-Management_Administrative_R&D Office ') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF04', 'GFB-04-Cafeteria (Dining Hall Building)') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF05', 'GFB-05-Health Center') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF06', 'GFB-06-Data Center') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF07', 'GFB-07-Facility Maintanance Office and Workshop') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF08', 'GFB-08-Fire Station') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF09', 'GFB-09-Heating Plant') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF10', 'GFB-10-Energetic Area Entrance Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF11', 'GFB-11-Security Tower (8 units)') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF12', 'GFB-12-Main Transformer Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13A', 'GFB-13A-Transformer Building-A') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13B', 'GFB-13B-Transformer Building-B') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13C', 'GFB-13C-Transformer Building-C') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13D', 'GFB-13D-Transformer Building-D') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13E', 'GFB-13E-Transformer Building-E') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13F', 'GFB-13F-Transformer Building-F') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13G', 'GFB-13G-Transformer Building-G') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13H', 'GFB-13H-Transformer Building-H') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'G13I', 'GFB-13I-Transformer Building-I') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF14', 'GFB-14-Water Tank Building (Potable water)') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF15', 'GFB-15-Fire Water Tank Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF16', 'GFB-16-Waste Water Purification Plant ') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF17', 'GFB-17-Industrial Waste Water Purification Plant ') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF18', 'GFB-18-Temporary Waste Holding Area ') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'GF19', 'GFB-19-Main Entrance Logistics') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IS01', 'ISB-01-Mixbowl_Mandrel and Tool Storage') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IS02', 'ISB-02-Inert Material Storage Building (Incoming Inspection and Calibration)') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IS03', 'ISB-03-Chemical Material Storage Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW01', 'IWB-01-Motor Case Production Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW1A', 'IWB-01A-Motor Case Preform Production Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW02', 'IWB-02-Motor Case Insulation and Composite') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW03', 'IWB-03-Spray Application Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW04', 'IWB-04-Control Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW05', 'IWB-05-Small Scale Propellant Assembly Test Control') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW06', 'IWB-06-Propellant Employee Office Building') ON CONFLICT(code) DO NOTHING;
INSERT INTO building_code (code, description) VALUES ( 'IW07', 'IWB-07-Warhead Employee Office Building') ON CONFLICT(code) DO NOTHING;
