services:
  - type: web
    name: dokuman-yonetim
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: rastgele_bir_gizli_anahtar
      - key: UPLOAD_FOLDER
        value: uploads
