"""Add document numbering fields to DocumentPolicy

Revision ID: 95fca84368c1
Revises: 0831af2d24c7
Create Date: 2025-03-28 00:06:25.747441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fca84368c1'
down_revision = '0831af2d24c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_format', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('separator', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('starting_number', sa.Integer(), nullable=True))
        batch_op.drop_column('policy_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_json', sa.TEXT(), nullable=False))
        batch_op.drop_column('starting_number')
        batch_op.drop_column('separator')
        batch_op.drop_column('date_format')
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###
