"""Add DocumentSequence model and update DocumentPolicy fields for numbering

Revision ID: bb79010f7dbc
Revises: c380a5ea781b
Create Date: 2025-03-28 02:51:34.802308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb79010f7dbc'
down_revision = 'c380a5ea781b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_document_policies')
    with op.batch_alter_table('document_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originator', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('document_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('discipline', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('building_code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('project_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('revision_format', sa.String(length=10), nullable=False))
        batch_op.drop_column('separator')
        batch_op.drop_column('prefix')
        batch_op.drop_column('date_format')
        batch_op.drop_column('starting_number')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('document_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('project_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        # UNIQUE constraint için artık isim veriyoruz:
        batch_op.create_unique_constraint('uq_document_number', ['document_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_number', type_='unique')
        batch_op.alter_column('project_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('document_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('document_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('date_format', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('prefix', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('separator', sa.VARCHAR(length=5), nullable=True))
        batch_op.drop_column('revision_format')
        batch_op.drop_column('project_code')
        batch_op.drop_column('building_code')
        batch_op.drop_column('discipline')
        batch_op.drop_column('document_type')
        batch_op.drop_column('originator')

    op.create_table('_alembic_tmp_document_policies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('revision_format', sa.VARCHAR(length=10), nullable=False),
    sa.Column('applied_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
