"""Add DocumentSequence model and update DocumentPolicy fields for numbering

Revision ID: c380a5ea781b
Revises: 95fca84368c1
Create Date: 2025-03-28 02:26:11.708475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c380a5ea781b'
down_revision = '95fca84368c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('originator', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('discipline', sa.String(length=50), nullable=False),
    sa.Column('building_code', sa.String(length=50), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('originator', 'document_type', 'discipline', 'building_code', name='uix_doc_seq')
    )
    with op.batch_alter_table('document_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('revision_format', sa.String(length=10), nullable=False))
        batch_op.drop_column('separator')
        batch_op.drop_column('starting_number')
        batch_op.drop_column('date_format')
        batch_op.drop_column('prefix')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('document_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('project_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['document_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('project_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('document_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('document_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_format', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('starting_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('separator', sa.VARCHAR(length=5), nullable=True))
        batch_op.drop_column('revision_format')
        batch_op.drop_column('project_code')

    op.drop_table('document_sequences')
    # ### end Alembic commands ###
