"""Remove document policy management

Revision ID: c5b360fe5cb3
Revises: f5bb990d57fd
Create Date: 2025-03-30 03:02:57.495412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b360fe5cb3'
down_revision = 'f5bb990d57fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_policies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_policies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('policy_json', sa.TEXT(), nullable=False),
    sa.Column('applied_at', sa.DATETIME(), nullable=True),
    sa.Column('originator', sa.VARCHAR(length=50), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('discipline', sa.VARCHAR(length=50), nullable=False),
    sa.Column('building_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('revision_format', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
